//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharepointUtilities.SP.Lists {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName="SP.Lists.ListsSoap")]
    public interface ListsSoap {
        
        // CODEGEN: Generating message contract since element name GetListCollectionResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetListCollection", ReplyAction="*")]
        SharepointUtilities.SP.Lists.GetListCollectionResponse GetListCollection(SharepointUtilities.SP.Lists.GetListCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/DeleteList", ReplyAction="*")]
        SharepointUtilities.SP.Lists.DeleteListResponse DeleteList(SharepointUtilities.SP.Lists.DeleteListRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateList", ReplyAction="*")]
        SharepointUtilities.SP.Lists.UpdateListResponse UpdateList(SharepointUtilities.SP.Lists.UpdateListRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/AddList", ReplyAction="*")]
        SharepointUtilities.SP.Lists.AddListResponse AddList(SharepointUtilities.SP.Lists.AddListRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetListAndView", ReplyAction="*")]
        SharepointUtilities.SP.Lists.GetListAndViewResponse GetListAndView(SharepointUtilities.SP.Lists.GetListAndViewRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetList", ReplyAction="*")]
        SharepointUtilities.SP.Lists.GetListResponse GetList(SharepointUtilities.SP.Lists.GetListRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/DeleteAttachment", ReplyAction="*")]
        SharepointUtilities.SP.Lists.DeleteAttachmentResponse DeleteAttachment(SharepointUtilities.SP.Lists.DeleteAttachmentRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetAttachmentCollection", ReplyAction="*")]
        SharepointUtilities.SP.Lists.GetAttachmentCollectionResponse GetAttachmentCollection(SharepointUtilities.SP.Lists.GetAttachmentCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/AddAttachment", ReplyAction="*")]
        SharepointUtilities.SP.Lists.AddAttachmentResponse AddAttachment(SharepointUtilities.SP.Lists.AddAttachmentRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateListItems", ReplyAction="*")]
        SharepointUtilities.SP.Lists.UpdateListItemsResponse UpdateListItems(SharepointUtilities.SP.Lists.UpdateListItemsRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetListItemChanges", ReplyAction="*")]
        SharepointUtilities.SP.Lists.GetListItemChangesResponse GetListItemChanges(SharepointUtilities.SP.Lists.GetListItemChangesRequest request);
        
        // CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetListItems", ReplyAction="*")]
        SharepointUtilities.SP.Lists.GetListItemsResponse GetListItems(SharepointUtilities.SP.Lists.GetListItemsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListCollectionRequestBody Body;
        
        public GetListCollectionRequest() {
        }
        
        public GetListCollectionRequest(SharepointUtilities.SP.Lists.GetListCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListCollectionRequestBody {
        
        public GetListCollectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListCollectionResponseBody Body;
        
        public GetListCollectionResponse() {
        }
        
        public GetListCollectionResponse(SharepointUtilities.SP.Lists.GetListCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetListCollectionResult;
        
        public GetListCollectionResponseBody() {
        }
        
        public GetListCollectionResponseBody(System.Xml.XmlElement GetListCollectionResult) {
            this.GetListCollectionResult = GetListCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteList", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.DeleteListRequestBody Body;
        
        public DeleteListRequest() {
        }
        
        public DeleteListRequest(SharepointUtilities.SP.Lists.DeleteListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        public DeleteListRequestBody() {
        }
        
        public DeleteListRequestBody(string listName) {
            this.listName = listName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteListResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.DeleteListResponseBody Body;
        
        public DeleteListResponse() {
        }
        
        public DeleteListResponse(SharepointUtilities.SP.Lists.DeleteListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteListResponseBody {
        
        public DeleteListResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateList", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.UpdateListRequestBody Body;
        
        public UpdateListRequest() {
        }
        
        public UpdateListRequest(SharepointUtilities.SP.Lists.UpdateListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.XmlElement listProperties;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.XmlElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.XmlElement updateFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Xml.XmlElement deleteFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string listVersion;
        
        public UpdateListRequestBody() {
        }
        
        public UpdateListRequestBody(string listName, System.Xml.XmlElement listProperties, System.Xml.XmlElement newFields, System.Xml.XmlElement updateFields, System.Xml.XmlElement deleteFields, string listVersion) {
            this.listName = listName;
            this.listProperties = listProperties;
            this.newFields = newFields;
            this.updateFields = updateFields;
            this.deleteFields = deleteFields;
            this.listVersion = listVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateListResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.UpdateListResponseBody Body;
        
        public UpdateListResponse() {
        }
        
        public UpdateListResponse(SharepointUtilities.SP.Lists.UpdateListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement UpdateListResult;
        
        public UpdateListResponseBody() {
        }
        
        public UpdateListResponseBody(System.Xml.XmlElement UpdateListResult) {
            this.UpdateListResult = UpdateListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddList", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.AddListRequestBody Body;
        
        public AddListRequest() {
        }
        
        public AddListRequest(SharepointUtilities.SP.Lists.AddListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class AddListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int templateID;
        
        public AddListRequestBody() {
        }
        
        public AddListRequestBody(string listName, string description, int templateID) {
            this.listName = listName;
            this.description = description;
            this.templateID = templateID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddListResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.AddListResponseBody Body;
        
        public AddListResponse() {
        }
        
        public AddListResponse(SharepointUtilities.SP.Lists.AddListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class AddListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement AddListResult;
        
        public AddListResponseBody() {
        }
        
        public AddListResponseBody(System.Xml.XmlElement AddListResult) {
            this.AddListResult = AddListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListAndViewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListAndView", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListAndViewRequestBody Body;
        
        public GetListAndViewRequest() {
        }
        
        public GetListAndViewRequest(SharepointUtilities.SP.Lists.GetListAndViewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListAndViewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string viewName;
        
        public GetListAndViewRequestBody() {
        }
        
        public GetListAndViewRequestBody(string listName, string viewName) {
            this.listName = listName;
            this.viewName = viewName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListAndViewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListAndViewResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListAndViewResponseBody Body;
        
        public GetListAndViewResponse() {
        }
        
        public GetListAndViewResponse(SharepointUtilities.SP.Lists.GetListAndViewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListAndViewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetListAndViewResult;
        
        public GetListAndViewResponseBody() {
        }
        
        public GetListAndViewResponseBody(System.Xml.XmlElement GetListAndViewResult) {
            this.GetListAndViewResult = GetListAndViewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(SharepointUtilities.SP.Lists.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        public GetListRequestBody() {
        }
        
        public GetListRequestBody(string listName) {
            this.listName = listName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(SharepointUtilities.SP.Lists.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(System.Xml.XmlElement GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAttachmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAttachment", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.DeleteAttachmentRequestBody Body;
        
        public DeleteAttachmentRequest() {
        }
        
        public DeleteAttachmentRequest(SharepointUtilities.SP.Lists.DeleteAttachmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteAttachmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string listItemID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string url;
        
        public DeleteAttachmentRequestBody() {
        }
        
        public DeleteAttachmentRequestBody(string listName, string listItemID, string url) {
            this.listName = listName;
            this.listItemID = listItemID;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAttachmentResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.DeleteAttachmentResponseBody Body;
        
        public DeleteAttachmentResponse() {
        }
        
        public DeleteAttachmentResponse(SharepointUtilities.SP.Lists.DeleteAttachmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteAttachmentResponseBody {
        
        public DeleteAttachmentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttachmentCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttachmentCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetAttachmentCollectionRequestBody Body;
        
        public GetAttachmentCollectionRequest() {
        }
        
        public GetAttachmentCollectionRequest(SharepointUtilities.SP.Lists.GetAttachmentCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetAttachmentCollectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string listItemID;
        
        public GetAttachmentCollectionRequestBody() {
        }
        
        public GetAttachmentCollectionRequestBody(string listName, string listItemID) {
            this.listName = listName;
            this.listItemID = listItemID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttachmentCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttachmentCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetAttachmentCollectionResponseBody Body;
        
        public GetAttachmentCollectionResponse() {
        }
        
        public GetAttachmentCollectionResponse(SharepointUtilities.SP.Lists.GetAttachmentCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetAttachmentCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetAttachmentCollectionResult;
        
        public GetAttachmentCollectionResponseBody() {
        }
        
        public GetAttachmentCollectionResponseBody(System.Xml.XmlElement GetAttachmentCollectionResult) {
            this.GetAttachmentCollectionResult = GetAttachmentCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAttachmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAttachment", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.AddAttachmentRequestBody Body;
        
        public AddAttachmentRequest() {
        }
        
        public AddAttachmentRequest(SharepointUtilities.SP.Lists.AddAttachmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class AddAttachmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string listItemID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] attachment;
        
        public AddAttachmentRequestBody() {
        }
        
        public AddAttachmentRequestBody(string listName, string listItemID, string fileName, byte[] attachment) {
            this.listName = listName;
            this.listItemID = listItemID;
            this.fileName = fileName;
            this.attachment = attachment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAttachmentResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.AddAttachmentResponseBody Body;
        
        public AddAttachmentResponse() {
        }
        
        public AddAttachmentResponse(SharepointUtilities.SP.Lists.AddAttachmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class AddAttachmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddAttachmentResult;
        
        public AddAttachmentResponseBody() {
        }
        
        public AddAttachmentResponseBody(string AddAttachmentResult) {
            this.AddAttachmentResult = AddAttachmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateListItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateListItems", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.UpdateListItemsRequestBody Body;
        
        public UpdateListItemsRequest() {
        }
        
        public UpdateListItemsRequest(SharepointUtilities.SP.Lists.UpdateListItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateListItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.XmlElement updates;
        
        public UpdateListItemsRequestBody() {
        }
        
        public UpdateListItemsRequestBody(string listName, System.Xml.XmlElement updates) {
            this.listName = listName;
            this.updates = updates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateListItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateListItemsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.UpdateListItemsResponseBody Body;
        
        public UpdateListItemsResponse() {
        }
        
        public UpdateListItemsResponse(SharepointUtilities.SP.Lists.UpdateListItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateListItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement UpdateListItemsResult;
        
        public UpdateListItemsResponseBody() {
        }
        
        public UpdateListItemsResponseBody(System.Xml.XmlElement UpdateListItemsResult) {
            this.UpdateListItemsResult = UpdateListItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListItemChangesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListItemChanges", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListItemChangesRequestBody Body;
        
        public GetListItemChangesRequest() {
        }
        
        public GetListItemChangesRequest(SharepointUtilities.SP.Lists.GetListItemChangesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListItemChangesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.XmlElement viewFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string since;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.XmlElement contains;
        
        public GetListItemChangesRequestBody() {
        }
        
        public GetListItemChangesRequestBody(string listName, System.Xml.XmlElement viewFields, string since, System.Xml.XmlElement contains) {
            this.listName = listName;
            this.viewFields = viewFields;
            this.since = since;
            this.contains = contains;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListItemChangesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListItemChangesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListItemChangesResponseBody Body;
        
        public GetListItemChangesResponse() {
        }
        
        public GetListItemChangesResponse(SharepointUtilities.SP.Lists.GetListItemChangesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListItemChangesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetListItemChangesResult;
        
        public GetListItemChangesResponseBody() {
        }
        
        public GetListItemChangesResponseBody(System.Xml.XmlElement GetListItemChangesResult) {
            this.GetListItemChangesResult = GetListItemChangesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListItems", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListItemsRequestBody Body;
        
        public GetListItemsRequest() {
        }
        
        public GetListItemsRequest(SharepointUtilities.SP.Lists.GetListItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string viewName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.XmlElement query;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.XmlElement viewFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rowLimit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Xml.XmlElement queryOptions;
        
        public GetListItemsRequestBody() {
        }
        
        public GetListItemsRequestBody(string listName, string viewName, System.Xml.XmlElement query, System.Xml.XmlElement viewFields, string rowLimit, System.Xml.XmlElement queryOptions) {
            this.listName = listName;
            this.viewName = viewName;
            this.query = query;
            this.viewFields = viewFields;
            this.rowLimit = rowLimit;
            this.queryOptions = queryOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListItemsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharepointUtilities.SP.Lists.GetListItemsResponseBody Body;
        
        public GetListItemsResponse() {
        }
        
        public GetListItemsResponse(SharepointUtilities.SP.Lists.GetListItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetListItemsResult;
        
        public GetListItemsResponseBody() {
        }
        
        public GetListItemsResponseBody(System.Xml.XmlElement GetListItemsResult) {
            this.GetListItemsResult = GetListItemsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ListsSoapChannel : SharepointUtilities.SP.Lists.ListsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ListsSoapClient : System.ServiceModel.ClientBase<SharepointUtilities.SP.Lists.ListsSoap>, SharepointUtilities.SP.Lists.ListsSoap {
        
        public ListsSoapClient() {
        }
        
        public ListsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.GetListCollectionResponse SharepointUtilities.SP.Lists.ListsSoap.GetListCollection(SharepointUtilities.SP.Lists.GetListCollectionRequest request) {
            return base.Channel.GetListCollection(request);
        }
        
        public System.Xml.XmlElement GetListCollection() {
            SharepointUtilities.SP.Lists.GetListCollectionRequest inValue = new SharepointUtilities.SP.Lists.GetListCollectionRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.GetListCollectionRequestBody();
            SharepointUtilities.SP.Lists.GetListCollectionResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).GetListCollection(inValue);
            return retVal.Body.GetListCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.DeleteListResponse SharepointUtilities.SP.Lists.ListsSoap.DeleteList(SharepointUtilities.SP.Lists.DeleteListRequest request) {
            return base.Channel.DeleteList(request);
        }
        
        public void DeleteList(string listName) {
            SharepointUtilities.SP.Lists.DeleteListRequest inValue = new SharepointUtilities.SP.Lists.DeleteListRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.DeleteListRequestBody();
            inValue.Body.listName = listName;
            SharepointUtilities.SP.Lists.DeleteListResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).DeleteList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.UpdateListResponse SharepointUtilities.SP.Lists.ListsSoap.UpdateList(SharepointUtilities.SP.Lists.UpdateListRequest request) {
            return base.Channel.UpdateList(request);
        }
        
        public System.Xml.XmlElement UpdateList(string listName, System.Xml.XmlElement listProperties, System.Xml.XmlElement newFields, System.Xml.XmlElement updateFields, System.Xml.XmlElement deleteFields, string listVersion) {
            SharepointUtilities.SP.Lists.UpdateListRequest inValue = new SharepointUtilities.SP.Lists.UpdateListRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.UpdateListRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.listProperties = listProperties;
            inValue.Body.newFields = newFields;
            inValue.Body.updateFields = updateFields;
            inValue.Body.deleteFields = deleteFields;
            inValue.Body.listVersion = listVersion;
            SharepointUtilities.SP.Lists.UpdateListResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).UpdateList(inValue);
            return retVal.Body.UpdateListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.AddListResponse SharepointUtilities.SP.Lists.ListsSoap.AddList(SharepointUtilities.SP.Lists.AddListRequest request) {
            return base.Channel.AddList(request);
        }
        
        public System.Xml.XmlElement AddList(string listName, string description, int templateID) {
            SharepointUtilities.SP.Lists.AddListRequest inValue = new SharepointUtilities.SP.Lists.AddListRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.AddListRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.description = description;
            inValue.Body.templateID = templateID;
            SharepointUtilities.SP.Lists.AddListResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).AddList(inValue);
            return retVal.Body.AddListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.GetListAndViewResponse SharepointUtilities.SP.Lists.ListsSoap.GetListAndView(SharepointUtilities.SP.Lists.GetListAndViewRequest request) {
            return base.Channel.GetListAndView(request);
        }
        
        public System.Xml.XmlElement GetListAndView(string listName, string viewName) {
            SharepointUtilities.SP.Lists.GetListAndViewRequest inValue = new SharepointUtilities.SP.Lists.GetListAndViewRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.GetListAndViewRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.viewName = viewName;
            SharepointUtilities.SP.Lists.GetListAndViewResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).GetListAndView(inValue);
            return retVal.Body.GetListAndViewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.GetListResponse SharepointUtilities.SP.Lists.ListsSoap.GetList(SharepointUtilities.SP.Lists.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public System.Xml.XmlElement GetList(string listName) {
            SharepointUtilities.SP.Lists.GetListRequest inValue = new SharepointUtilities.SP.Lists.GetListRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.GetListRequestBody();
            inValue.Body.listName = listName;
            SharepointUtilities.SP.Lists.GetListResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.DeleteAttachmentResponse SharepointUtilities.SP.Lists.ListsSoap.DeleteAttachment(SharepointUtilities.SP.Lists.DeleteAttachmentRequest request) {
            return base.Channel.DeleteAttachment(request);
        }
        
        public void DeleteAttachment(string listName, string listItemID, string url) {
            SharepointUtilities.SP.Lists.DeleteAttachmentRequest inValue = new SharepointUtilities.SP.Lists.DeleteAttachmentRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.DeleteAttachmentRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.listItemID = listItemID;
            inValue.Body.url = url;
            SharepointUtilities.SP.Lists.DeleteAttachmentResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).DeleteAttachment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.GetAttachmentCollectionResponse SharepointUtilities.SP.Lists.ListsSoap.GetAttachmentCollection(SharepointUtilities.SP.Lists.GetAttachmentCollectionRequest request) {
            return base.Channel.GetAttachmentCollection(request);
        }
        
        public System.Xml.XmlElement GetAttachmentCollection(string listName, string listItemID) {
            SharepointUtilities.SP.Lists.GetAttachmentCollectionRequest inValue = new SharepointUtilities.SP.Lists.GetAttachmentCollectionRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.GetAttachmentCollectionRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.listItemID = listItemID;
            SharepointUtilities.SP.Lists.GetAttachmentCollectionResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).GetAttachmentCollection(inValue);
            return retVal.Body.GetAttachmentCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.AddAttachmentResponse SharepointUtilities.SP.Lists.ListsSoap.AddAttachment(SharepointUtilities.SP.Lists.AddAttachmentRequest request) {
            return base.Channel.AddAttachment(request);
        }
        
        public string AddAttachment(string listName, string listItemID, string fileName, byte[] attachment) {
            SharepointUtilities.SP.Lists.AddAttachmentRequest inValue = new SharepointUtilities.SP.Lists.AddAttachmentRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.AddAttachmentRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.listItemID = listItemID;
            inValue.Body.fileName = fileName;
            inValue.Body.attachment = attachment;
            SharepointUtilities.SP.Lists.AddAttachmentResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).AddAttachment(inValue);
            return retVal.Body.AddAttachmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.UpdateListItemsResponse SharepointUtilities.SP.Lists.ListsSoap.UpdateListItems(SharepointUtilities.SP.Lists.UpdateListItemsRequest request) {
            return base.Channel.UpdateListItems(request);
        }
        
        public System.Xml.XmlElement UpdateListItems(string listName, System.Xml.XmlElement updates) {
            SharepointUtilities.SP.Lists.UpdateListItemsRequest inValue = new SharepointUtilities.SP.Lists.UpdateListItemsRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.UpdateListItemsRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.updates = updates;
            SharepointUtilities.SP.Lists.UpdateListItemsResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).UpdateListItems(inValue);
            return retVal.Body.UpdateListItemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.GetListItemChangesResponse SharepointUtilities.SP.Lists.ListsSoap.GetListItemChanges(SharepointUtilities.SP.Lists.GetListItemChangesRequest request) {
            return base.Channel.GetListItemChanges(request);
        }
        
        public System.Xml.XmlElement GetListItemChanges(string listName, System.Xml.XmlElement viewFields, string since, System.Xml.XmlElement contains) {
            SharepointUtilities.SP.Lists.GetListItemChangesRequest inValue = new SharepointUtilities.SP.Lists.GetListItemChangesRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.GetListItemChangesRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.viewFields = viewFields;
            inValue.Body.since = since;
            inValue.Body.contains = contains;
            SharepointUtilities.SP.Lists.GetListItemChangesResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).GetListItemChanges(inValue);
            return retVal.Body.GetListItemChangesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharepointUtilities.SP.Lists.GetListItemsResponse SharepointUtilities.SP.Lists.ListsSoap.GetListItems(SharepointUtilities.SP.Lists.GetListItemsRequest request) {
            return base.Channel.GetListItems(request);
        }
        
        public System.Xml.XmlElement GetListItems(string listName, string viewName, System.Xml.XmlElement query, System.Xml.XmlElement viewFields, string rowLimit, System.Xml.XmlElement queryOptions) {
            SharepointUtilities.SP.Lists.GetListItemsRequest inValue = new SharepointUtilities.SP.Lists.GetListItemsRequest();
            inValue.Body = new SharepointUtilities.SP.Lists.GetListItemsRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.viewName = viewName;
            inValue.Body.query = query;
            inValue.Body.viewFields = viewFields;
            inValue.Body.rowLimit = rowLimit;
            inValue.Body.queryOptions = queryOptions;
            SharepointUtilities.SP.Lists.GetListItemsResponse retVal = ((SharepointUtilities.SP.Lists.ListsSoap)(this)).GetListItems(inValue);
            return retVal.Body.GetListItemsResult;
        }
    }
}
